### ISSUE TITLE
Potential Trojan ?

### ISSUE THREAD

**Issue by nononymousse** [Romanitho/Winget-Install-GUI#56]
Hi,

i have installed WiGui yesterday but i just got jusr now a alert from windows defender telling me wigui is a trojan, And with a quick analyse with virustotal telling me there is 13 vendor (from 66) detecting it as malicious (and some as malware too)

link to the result :
https://www.virustotal.com/gui/file/c901898c71f93ec8815ab17e5328984ced2d1fff679d52e1d10383effe2e3080

**Comment by Romanitho** [comment]
Hi,

Yes, because it is a PowerShell script converted to EXE, some antivirus might detect bad things. That's why I give the script PowerShell that you can run standalone AND the method used to compile the EXE. So, if you don't trust the EXE, run the PowerShell script directly 😊

Let me know if it helps.

**Comment by nononymousse** [comment]
thanks for your answer, it really reassures me ^^

tbh i will keep it cuz it's more convinient for me (i have put the app in the program files folder and on my start menu so i can remember it's there 😅)
