### ISSUE TITLE
Windows defender flags it as infected by Trojan:Win32/Wacatac.B!ml

### ISSUE THREAD

**Issue by cheskote** [Romanitho/Winget-Install-GUI#84]
Trying to download v1.9.2 Windows Defender flags it as infected by Trojan:Win32/Wacatac.B!ml

**Comment by cheskote** [comment]
More antivirus report it as infected: https://www.virustotal.com/gui/file/7cff96e464fc660c0a06617c6d7370f8d911fdd71884443c9ac9f13eb2f61fc6/detection

**Comment by Romanitho** [comment]
Use ps1

I will stop creating exe

**Comment by DandelionSprout** [comment]
From my experiences, Microsoft Defender tends to false-positive ***a lot*** of programs as Wacatac specifically, so goodness know how to make Microsoft Defender's devs get their stuff together.

**Comment by rohancragg** [comment]
> It wasn't super-easy to find the file whitelisting menu in Microsoft Defender, but I eventually found it at "Virus and Threat Protection" → "Settings for virus and threat protection" section → "Manage settings" → "Add or remove exceptions" → "+ Add exception", and then choose WiGui.exe.

You can only whitelist a file already on your machine and Defender immediately Quarantines it so instead I disabled Real-time protection so that I could download WiGui.exe and then I was able to use WiGui to install Winget-AutoUpdate whcih is what I was originally trying to do.

**Comment by AndrewDemski-ad-gmail-com** [comment]
IMHO
That shortcut should be generated locally.
That will solve the problem with distribution.

**Comment by DandelionSprout** [comment]
It wasn't exactly to find out where to *report* false positives to Microsoft **either**, but I eventually dug my way to https://www.microsoft.com/en-us/wdsi/filesubmission/?persona=HomeUser

<details><summary>Somewhat large screenshot of the report I sent them:</summary>

![image](https://github.com/Romanitho/Winget-Install-GUI/assets/22780683/acca4dcf-e3cc-452b-9240-efe5531a2f82)

</details>

(I somehow embarrassingly managed to write 366 instead of 396, but still.)
